# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d9cda29f98d7263f340898cc025204ea82e8e4276a150c270dbcb0f2b1ddff5071b9ccc9adb59dbee198c52e3f4f3d44f5014274deba9fc36e1c83fb00f811f

test:
  secret_key_base: 0abd6b77e8d681a78939bd66f7ee25ec3aec2efaac50a4be2f8057edf377fddec1744d987e6ec38e9bca1c2b42909a90facec503e36c18fbfc099b8a05ffdd0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
